export const PAGE_SIZE = 10

export const INTERVAL_CHECK_NOTIFICATIONS = 60000

export enum PAGES {
  ROOT = '',
  HOME = 'home',
  REGISTRATION = 'registration',
  SWAGGER = 'swagger',
  STORYBOOK = 'storybook',
  APPSTORE = 'appstore',
  MARKETPLACE = 'marketplace',
  APP_MARKETPLACE = 'appmarketplace',
  SERVICE_MARKETPLACE = 'servicemarketplace',
  DATASPACE_MARKETPLACE = 'dataspacemarketplace',
  APP_DETAIL = 'appdetail',
  DATACATALOG = 'datacatalog',
  DATA_MANAGEMENT = 'datamanagement',
  DIGITALTWIN = 'digitaltwin',
  SEMANTICHUB = 'semantichub',
  DEVELOPERHUB = 'developerhub',
  CONNECTOR = 'connector',
  ACCOUNT = 'account',
  USER_DETAILS = 'userdetails',
  NOTIFICATIONS = 'notifications',
  ORGANIZATION = 'organization',
  PARTNER_NETWORK = 'partnernetwork',
  USER_MANAGEMENT = 'usermanagement',
  TECHNICAL_USER_MANAGEMENT = 'technicaluser',
  TECHNICAL_SETUP = 'technicalsetup',
  TECHNICAL_USER_DETAILS = 'userdetails',
  APPLICATION_REQUESTS = 'applicationrequests',
  APP_USER_MANAGEMENT = 'appusermanagement',
  INVITE = 'invite',
  ADMINISTRATION = 'admin',
  HELP = 'help',
  CONTACT = 'contact',
  IMPRINT = 'imprint',
  PRIVACY = 'privacy',
  TERMS = 'terms',
  COOKIE_POLICY = 'cookiepolicy',
  THIRD_PARTY_LICENSES = 'thirdpartylicenses',
  SETTINGS = 'settings',
  DEVELOPER = 'developer',
  TEST = 'test',
  TRANSLATOR = 'translator',
  LOGOUT = 'logout',
  ERROR = 'error',
  APP_MANAGEMENT = 'appmanagement',
  APPOVERVIEW = 'appoverview',
  APPRELEASEPROCESS = 'appreleaseprocess',
}

export enum OVERLAYS {
  NONE = 'none',
  ADD_USER = 'add_user',
  ADD_APP_USER_ROLES = 'add_app_user_roles',
  EDIT_APP_USER_ROLES = 'edit_app_user_roles',
  USER = 'user',
  NEWS = 'news',
  ADD_BPN = 'add_bpn',
  INVITE = 'invite',
  PARTNER = 'partner',
  APP = 'app',
  TECHUSER = 'techuser',
}

export enum ACTIONS {
  LANG_DE = 'Lang_de',
  LANG_EN = 'Lang_en',
  SIGNOUT = 'SignOut',
}

export enum ROLES {
  EVERYONE = '*',
  CX_ADMIN = 'CX Admin',
  ADMIN_CONNECTOR = 'Admin - Connector Setup',
  ADMIN_USER = 'Admin - User Management',
  INVITE_NEW_PARTNER = 'invite_new_partner',
  SETUP_IDP = 'setup_idp',
  SETUP_CLIENT = 'setup_client',
  APPSTORE_VIEW = 'view_apps',
  APPSTORE_VIEW_SERVICES = 'view_services',
  APPSTORE_VIEW_DATASPACES = 'view_dataspaces',
  APPSTORE_ADD = 'add_app',
  APPSTORE_EDIT = 'edit_apps',
  APPSTORE_FILTER = 'filter_apps',
  APPSTORE_DELETE = 'delete_apps',
  CONNECTOR_SETUP = 'setup_connector',
  DATACATALOG_VIEW = 'view_data_catalog',
  DIGITALTWIN_VIEW = 'view_digital_twin',
  DIGITALTWIN_ADD = 'add_digital_twin',
  DIGITALTWIN_DELETE = 'delete_digital_twin',
  SEMANTICHUB_VIEW = 'view_semantic_model',
  SEMANTICHUB_ADD = 'add_semantic_model',
  SEMANTICHUB_DELETE = 'delete_semantic_model',
  USERMANAGEMENT_VIEW = 'view_user_management',
  USERMANAGEMENT_ADD = 'add_user_account',
  USERMANAGEMENT_DELETE = 'delete_user_account',
  USERMANAGEMENT_VIEW_USER_ACCOUNT = 'view_user_account',
  MODIFY_USER_ACCOUNT = 'modify_user_account',
  ORGANIZATION_VIEW = 'view_organization',
  PARTNER_NETWORK_VIEW = 'view_partner_network',
  DEVELOPER = 'catenax_developer',
  TECHNICAL_SETUP_VIEW = 'view_technical_setup',
  FE_DEVELOPER = 'FE Developer',
  VIEW_APP_RELEASE = 'view_app_release',
}

export enum HINTS {
  COMING_SOON = 'coming_soon',
}
