#
# Dockerfile with prebuilt webapp
#
# usage:
#        yarn
#        yarn build
#        yarn build:docker:prebuilt
#

FROM nginxinc/nginx-unprivileged:alpine

COPY cx-portal/build /usr/share/nginx/html
