#
# Dockerfile with prebuilt webapp
#
# usage:
#        yarn
#        yarn build
#        yarn build:docker:prebuilt
#

FROM nginxinc/nginx-unprivileged:alpine
COPY conf/nginx.conf /etc/nginx/conf.d/default.conf
COPY cx-portal/build /usr/share/nginx/html
