# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: pr checks

on: pull_request

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn

      - name: Build Library
        run: yarn build:lib

      - name: Unit Tests
        run: yarn test:ci
